### ISSUE TITLE
fix diagonal offset behaviour

### ISSUE THREAD

**Issue by olijeffers0n** [olijeffers0n/PatheticAPI#32]
allowingDiagonal is skipping blocks which therefore can't be processed by the strategy. means a path can go through walls ignoring the strategy etc.

**Comment by bsommerfeld** [comment]
this issue has been fixed with the following commits:
- https://github.com/patheloper/pathetic/commit/8626a963400274313797a1ae487a5d351d98fc0c
- https://github.com/patheloper/pathetic/commit/0abdaec399c41f286668bcf58735a97e033e7937
- https://github.com/patheloper/pathetic/commit/0e4c6347d24ba825ac43bc1e341a77e5586485d2
